@extends('landingfo.template.head')
@include('landingfo.template.body')
@include('landingfo.template.modalundangan')
@include('landingfo.template.header')
@include('landingfo.sections.home')
@include('landingfo.template.footer')
